### ISSUE TITLE
Initial Login Fails

### ISSUE THREAD

**Issue by amaisonneuve** [LinxHQ/linxbooks#1]
Error:

CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'linxbooks.YiiSession' doesn't exist. The SQL statement executed was: SELECT *
FROM `YiiSession`
WHERE id=:id

The tables are created but the login fails

**Comment by amaisonneuve** [comment]
this has been fixed in my fork.

**Comment by josephpnc** [comment]
@thongnvlb @HoDucTien37 please take a look at the fix in Alain's fork, and see if we should apply the same to the main branch.

**Comment by HoDucTien37** [comment]
Hi, 
The issue has been fixed. Please download code again and reinstall it. Let us know if you have any inquiries.
Thanks,

**Comment by amaisonneuve** [comment]
It would seem that in the latest code this issue is not corrected, i had to edit the file again and have the table name to lower case.

**Comment by HoDucTien37** [comment]
Thanks.

**Comment by josephpnc** [comment]
@amaisonneuve are you running this on windows?

**Comment by HoDucTien37** [comment]
@amaisonneuve we fixed it.
Thanks,

**Comment by amaisonneuve** [comment]
no. centos
