### ISSUE TITLE
Issues #5 and #1 are back

### ISSUE THREAD

**Issue by hjone72** [LinxHQ/linxbooks#13]
Hi,

It seems like commit [91d06a7](https://github.com/LinxHQ/linxbooks/tree/91d06a73f3d203caa080bc4b06fce1091e650a64) has brought back both issue #1 and #5 
Hope this can be resolved quickly.

Thanks,

**Comment by josephpnc** [comment]
@nhuhtlb @HoDucTien37

**Comment by josephpnc** [comment]
@mrtran151190

**Comment by linxbooksadmin** [comment]
I've uploaded latest ver to github. Please read the README for installation instruction. the current web install interface is not updated yet.
