### ISSUE TITLE
Invite Member fails

### ISSUE THREAD

**Issue by hjone72** [LinxHQ/linxbooks#15]
When you click "Invite member" you get a:
Property "AccountInvitation.account_invitation_subscription_id" is not defined.

![image](https://cloud.githubusercontent.com/assets/4342811/15109520/12f26bc2-161f-11e6-94f8-4dc3db3741ad.png)

**Comment by josephpnc** [comment]
Thanks We'll attend to it as soon as we can. @nhuhtlb @HoDucTien37

**Comment by josephpnc** [comment]
@mrtran151190 for follow up

**Comment by linxbooksadmin** [comment]
I've uploaded latest ver to github. Please read the README for installation instruction. the current web install interface is not updated yet.

Can you reinstall and try again? Or if you want to update just the code, just download the code only.

**Comment by auzadventure** [comment]
you can use git pull to sync it with your current files.
