### ISSUE TITLE
Property "AccountInvitation.account_invitation_subscription_id" is not defined.

### ISSUE THREAD

**Issue by sibidharan** [LinxHQ/linxbooks#18]
I tried to invite members from Admin Account, and it end up in error `Property "AccountInvitation.account_invitation_subscription_id" is not defined.`

Here is the stack trace: 
[CException.pdf](https://github.com/LinxHQ/linxbooks/files/462045/CException.pdf)

**Comment by josephpnc** [comment]
This must have been due to our removal of the subscription feature from the community solution. My apologies. We'll try to rectify the situation soon. We are a little bit over stretched right now.
Joseph

Sent from my Samsung device

-------- Original message --------

**Comment by josephpnc** [comment]
@mrtran151190 for follow up

**Comment by linxbooksadmin** [comment]
I've uploaded latest ver to github. Please read the README for installation instruction. the current web install interface is not updated yet.
