### ISSUE TITLE
Remove the User Entry

### ISSUE THREAD

**Issue by amaisonneuve** [LinxHQ/linxbooks#2]
This is a security violation, please remove this statment from the SQL file that is run at install time. I have removed it from my fork.

INSERT INTO `lb_sys_accounts` (`account_id`, `account_email`, `account_password`, `account_created_date`, `account_timezone`, `account_language`, `account_status`) VALUES
(1, 'thongnv@linxhq.com', '$2a$13$qpeEkJRJxEX9EKyWqQZHC.2IAoGyhhWlSWtnavgROUk98Tp0UPODy', '2015-06-15 04:15:17', NULL, NULL, 1);

**Comment by josephpnc** [comment]
Thanks for spotting that! @HoDucTien37 can you update the main branch? Thanks!

**Comment by HoDucTien37** [comment]
Hi, 
This has been updated. Please download code again and reinstall it. Let us know if you have any inquiries.
Thanks,
