### ISSUE TITLE
Problem with Installation

### ISSUE THREAD

**Issue by tenkodoy** [LinxHQ/linxbooks#21]
Hello I'm having problems with installation. Can you please help.
Also can you give the default username and password

**Comment by josephpnc** [comment]
Hi what problem are you facing? Because the installation process should have asked you to enter your own password. If not, try admin/admin123.

**Comment by tenkodoy** [comment]
it keeps on telling me no database found, if i try to add a db in mysql too, gives me some error. Can you please give me the step by step installation together with the password

**Comment by josephpnc** [comment]
I think the version on github might be old. Our team is too busy at the moment. You can download the attached version, then import 
sql/linxbooks20161221.sql

 into the database.

https://drive.google.com/open?id=0B0FXaLvmrtbUdXlLaVpmTVhOazA <https://drive.google.com/open?id=0B0FXaLvmrtbUdXlLaVpmTVhOazA>

Hope that helps.

**Comment by linxbooksadmin** [comment]
I've uploaded latest ver to github. Please read the README for installation instruction. the current web install interface is not updated yet.
