### ISSUE TITLE
Mutiple Company Selector on right side

### ISSUE THREAD

**Issue by auzadventure** [LinxHQ/linxbooks#24]
Below Admin >>

Shows multiple companies. Some do not have income customer or expenses. Quite confusing, should remove and only allow 1 company for invoice/expenses

**Comment by linxbooksadmin** [comment]
fixed. It's just the imported database .sql has more than 1 company. You can either check out the code and reinstall, or run this sql in your database

DELETE FROM lb_sys_account_subscriptions WHERE account_id != 1
