### ISSUE TITLE
How do you edit Expenses > Catagory 

### ISSUE THREAD

**Issue by auzadventure** [LinxHQ/linxbooks#27]
http://localhost/test/linxbooks/linxbooks/index.php/1/lbExpenses/create

1. How do you edit and input dropdown items for expenses? 
  - should put a link to edit it 

2. Should add additional sub-category bookkeeping

**Comment by linxbooksadmin** [comment]
Admin (or your name at top right hand corner) > Configuration > tab List > expenses_category.

**Comment by auzadventure** [comment]
should put a link next to the field to edit.

**Comment by josephpnc** [comment]
We’ll probably put a new link within the dropdown itself, at the top.

**Comment by linxbooksadmin** [comment]
done.
