### ISSUE TITLE
Employee Module / Function not comprehensive - remove 

### ISSUE THREAD

**Issue by auzadventure** [LinxHQ/linxbooks#28]
We should remove 

http://localhost/test/linxbooks/linxbooks/index.php/1/lbExpenses/create Employee Report 

The employee function is too simple and not suitable for usage. I think we just remove the entire system.
The user can select expense > wages > john to track expenses.

**Comment by linxbooksadmin** [comment]
where did u access it from, which part on the UI?

**Comment by linxbooksadmin** [comment]
removed.
