### ISSUE TITLE
Missing Column

### ISSUE THREAD

**Issue by amaisonneuve** [LinxHQ/linxbooks#5]
Clicking 'My Account'

CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't.lb_record_primary_key' in 'on clause'. The SQL statement executed was: SELECT COUNT(*) FROM `lb_account_roles` `t` LEFT JOIN lb_core_entities c ON lb_entity_type = 'accountRoles' AND c.lb_entity_primary_key = t.lb_record_primary_key WHERE (accout_id = 1) AND (c.lb_subscription_id=:ycp5)

**Comment by josephpnc** [comment]
@thongnvlb please take a look.

**Comment by HoDucTien37** [comment]
Thanks,
 the issue has been fixed.
